import { Avatar } from '../Avatar'
import type { Mentor } from '../../types'

/** Mentor detail shown beside the conversation. */
export function MentorPanel({ mentor }: { mentor: Mentor }) {
  return (
    <div className="space-y-6 p-5">
      <div className="flex items-center gap-3">
        <Avatar name={mentor.name} src={mentor.image_url} size={52} />
        <div className="min-w-0">
          <h2 className="truncate font-semibold tracking-tight">{mentor.name}</h2>
          <p className="truncate text-sm text-muted">{mentor.expertise}</p>
        </div>
      </div>

      <Field label="Perspective" value={mentor.perspective} />
      <Field label="Style" value={mentor.style} />

      <p className="border-t border-line pt-4 text-xs leading-relaxed text-faint">
        Replies are generated by an AI model drawing on {mentor.name}&rsquo;s published work. They
        are not {mentor.name}&rsquo;s own words.
      </p>
    </div>
  )
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <h3 className="text-xs font-semibold uppercase tracking-wider text-faint">{label}</h3>
      <p className="mt-1.5 text-sm leading-relaxed text-muted">{value}</p>
    </div>
  )
}
